language: python
python:
  - "3.5"
services: mysql

env:
  global:
    - BUILD_ON_TRAVIS=true
  install:
  - pip install -q -r requirements.txt
before_script:
  - mysql -e 'create database travis_ci_db;'
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - python manage.py test